### ISSUE TITLE
V1.0.474 not compatible with composer v2, v1.1.6 works fine.

### ISSUE THREAD

**Issue by wverhoogt** [mik-p/docker-wintercms#3]
If I try to install the builder plugin using "composer require winter/wn-builder-plugin", the installation fails with the message:
`Problem 1
    - Root composer.json requires winter/wn-builder-plugin ^2.0 -> satisfiable by winter/wn-builder-plugin[v2.0.0, v2.0.1, v2.0.2].
    - winter/wn-cms-module[v1.0.473, ..., 1.0.x-dev] require composer/installers dev-main as 1.0 -> satisfiable by composer/installers[dev-main].
    - Conclusion: don't install composer/installers dev-main (conflict analysis result)
    - Root composer.json requires winter/wn-cms-module ~1.0.472 -> satisfiable by winter/wn-cms-module[v1.0.473, v1.0.474, 1.0.x-dev].`
The same command works fine on a freshly cloned winter 1.1.6.
Perhaps base the container on that version?

**Comment by mik-p** [comment]
Hi,

You can use the develop tag which is roughly 1.1.6. The containers will be updated for the next winter release. what happened was, the way the 'automated' (not really) update works at the moment, the latest tag from github is used and the 1.0.474 is technically the latest. I would have liked to have skipped it tbh.

The releases were a day apart and I missed the v1.1.6. This is caused by the way the tagging has been done on the winter repo. If I were to fix this I would be creating a fork in the automation to handle the two build cases which I would like to avoid seeing as the v1.0.xx is for legacy support.

**Comment by mik-p** [comment]
I fixed it a different way. As you say the image is now based on 1.1.6
